server:
  port: 7001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka-7001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机配置