server:
  port: 9666
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9666.com
    prefer-ip-address: true
zuul:
  ignored-services: "*"
  prefix: "/services"
  routes: #路由的配置
    user.serviceId: buythis-plat
    user.path: /user/**